#!/bin/sh
# Regenerates the share image and icons from the SVG sources in this folder.
# Requires rsvg-convert + ImageMagick (brew install librsvg imagemagick) and the
# fonts referenced in the SVGs (Georgia / Inter / Menlo). Sources were generated by
# an MDO3D SEO-sweep script; edit the SVGs directly to change copy or colors.
set -e
cd "$(dirname "$0")"
OUT=..
for f in *og-image.svg; do rsvg-convert -w 1200 -h 630 "$f" -o "$OUT/${f%.svg}.png"; done
# Icons: existing images/icons/* PNGs are reused (see site.webmanifest); no vector mark exists.
